apiVersion: v1
kind: Service
metadata:
  name: execution
spec:
  selector:
    app: execution
  ports:
    - name: p2p
      protocol: TCP
      port: 30303
      targetPort: 30303
    - name: rpc
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: engine
      protocol: TCP
      port: 8551
      targetPort: 8551
    - name: ws
      protocol: TCP
      port: 8546
      targetPort: 8546