apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ethereum

helmCharts:
  - name: ethereum
    namespace: ethereum
    valuesFile: charts/ethereum/values.yaml

resources:
  - base/namespace.yaml