name: Ethereum CI

on:
  push:
    paths:
      - '.github/**'
      - 'Makefile'
      - 'kustomize/dev/ethereum/**'
      - 'scripts/**'

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
  
      - name: Helm Lint
        run: |
          helm lint kustomize/dev/ethereum/charts/ethereum

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install ShellCheck
        run: sudo apt-get install shellcheck

      - name: ShellCheck
        run: |
          find scripts/ -name "*.sh" -print0 | xargs -0 shellcheck